_schema: default
glossary_term_name: Schema
term_description: >-
  A structured definition that describes the format, fields, and validation rules for content in CloudCannon. Schemas help ensure consistent data entry and provide better editing interfaces for content creators.
documentation_link: /developer/articles/split-your-configuration-file/
