_schema: default
glossary_term_name: Schema
term_description: >-
  A predefined template that determines what content should populate a new *Collection* file. You can configure several *Schemas* for each *Collection*, creating a list of file templates for you and your team.
documentation_link: /developer-articles/what-is-a-schema/
