_schema: default
glossary_term_name: Site
term_description: >-
  A website in CloudCannon that includes all the files, content, configuration, and settings needed to edit, build, and host a complete website.
documentation_link: /documentation/developer-articles/what-is-headless-mode/
