_schema: default
glossary_term_name: Site
term_description: >-
  A website project in CloudCannon that includes all the files, content, configuration, and settings needed to build and host a complete website. Sites can be connected to Git repositories and managed through CloudCannon's interface.
documentation_link: /developer/articles/what-is-headless-mode/
