_schema: default
glossary_term_name: Build
term_description: >-
  The process of transforming source files (Markdown, templates, assets) into a complete static website using a static site generator. In CloudCannon, builds are triggered automatically when content changes or can be manually initiated.
documentation_link: /developer/articles/configure-your-first-build/
