_schema: default
glossary_term_name: Build
term_description: >-
  The process of converting all your *Site* files into a single, functional website using the method specified by your SSG. Building on CloudCannon is optional, but is required for specific features, such as the *Visual Editor*, preview screenshots for output files in your *Collection Browser*, and the *Testing Domain* and *Custom Domain*.
documentation_link: /developer-articles/what-is-a-site-build/
