_snippets_imports:
  mdx: true

_snippets:
  code_block:
    snippet: "<comp.CodeBlock [[args]]>\n[[backticks]]\n[[inner]]\n[[backticks]]\n[[annotations]]</comp.CodeBlock>"
    inline": false
    preview:
      text:
        - key: source
        - Code Block
      subtext: 
        - key: content
      icon: code
    _inputs: 
      content: 
        type: code
      annotations:
        type: array
        comment: "Optional annotations to show below the code block. Link them with a comment like `/*1*/`, `//1`, `#1`, or `<!--1-->`"
        options:
          structures:
            values:
              - _inputs:
                  annotation_content:
                    type: markdown
                  number:
                    comment: "Match to a comment of `/*1*/`, `//1`, `#1`, or `<!--1-->` in the code block"
                    type: text
                preview:
                  icon: campaign
                  text:
                    - key: number
                    - Unconfigured
                  subtext:
                    - key: annotation_content
                    - Empty
                value: 
                  number: 1
                  annotation_content: ""
    params:
      backticks:
        parser: repeating_literal
        options:
          literal: "`"
          minimum: 3
          default: 10
      args:
        parser: key_values
        options:
          models:
            - editor_key: language
              type: string
              default: ""
              optional: true
            - editor_key: source
              type: string
              default: ""
              optional: true
              remove_empty: true
            - editor_key: frameless
              type: boolean
              optional: true
              remove_empty: true
          format:
            ref: mdx_format
      inner:
        parser: content
        options:
          editor_key: content
          allow_nested: false
          raw: true
          forbidden_tokens:
            - "```"
          style:
            output: block
            block:
              leading: "\n"
              trailing: "\n"
              indent: ""
      annotations:
        parser: optional
        options: 
          snippet: "[[annotation_repeat]]"
      annotation_repeat:
        parser: repeating
        options:
          default_length: 0
          editor_key: annotations
          snippet: "<comp.Annotation [[annotation_args]]>[[annotation_content]]</comp.Annotation>"
          style:
            between: "\n"
            block:
              leading: ""
              trailing: "\n"
      annotation_args:
        parser: key_values
        options:
          models:
            - editor_key: number
              type: string
          format: 
            ref: mdx_format
      annotation_content:
        parser: content
        options:
          editor_key: annotation_content
          allow_nested: false
          raw: true
          style:
            output: block
            block:
              leading: "\n"
              trailing: "\n"
              indent: "  "

data_config:
  article_topics:
    path: /_data/article_topics.yml
    
_select_data:
  docs_ssgs: ssg_data.ssgs
  docs_guide_series: guide_series_data.series
  docshots_status: 
    - name: 'Needs docshots'
      icon: 'add_a_photo'
      icon_color: '#cc3232'
    - name: 'Not applicable'
      icon: 'no_photography'
      icon_color: '#e7b416'
    - name: 'Added!'
      icon: 'photo_camera'
      icon_color: '#2dc937'

  diataxis_category:
    - name: 'Explanation'
      icon: 'lightbulb'
      icon_color: '#06d6a0'
    - name: 'Guide'
      icon: 'handshake'
      icon_color: '#26547c'
    - name: 'Instructions'
      icon: 'info'
      icon_color: '#ef476f'
    - name: 'Reference'
      icon: 'fact_check'
      icon_color: '#ffd166'

  key_value_type:
    - name: 'Array'
      icon: 'data_array'
    - name: 'Boolean'
      icon: 'check_box'
    - name: 'Date'
      icon: 'event'
    - name: 'Number'
      icon: '123'
    - name: 'Object'
      icon: 'add_box'
    - name: 'String'
      icon: 'abc'
    - name: 'Array of Numbers'
      icon: '123'
    - name: 'Array of Objects'
      icon: 'add_box'
    - name: 'Array of Strings'
      icon: 'abc'

collections_config:
  pages:
    path: ""
    glob:
      - "index.mdx"
      - "guides.mdx"
      - "changelog/*"
      - "articles/index.mdx"
      - "404/*"
  common_content:
    paths:
      dam_uploads: "[collection|slugify]/{date|year}/{date|month}/[asset-filename]"
    path: "_common_content"
    output: false
    icon: "copy_all"
    schemas:
      default:
        path: ".cloudcannon/schemas/common_content.mdx"
    _inputs:
      content_name:
        comment: "Give this piece of reusable content a descriptive name, as this is what you will select when inserting it in a page"
      parameters:
        type: object
        comment: "Define any keys you created in Substitution snippets here"
        options:
          subtype: mutable
          entries:
            structures:
              values:
                - value:
                    comment: null
                    type: null
                  _inputs:
                    comment:
                      comment: "Text that will be shown alongside this parameter when using this piece of custom content"
                    type:
                      comment:
                        "The CloudCannon input type that should be used for editing this parameter"
  articles:
    path: articles
    output: true
    icon: article
    url: "/articles/[slug]/"
    schemas:
      default:
        path: ".cloudcannon/schemas/article.mdx"
      instructions:
        path: ".cloudcannon/schemas/article-instructions.mdx"
    _inputs:
      "$.title":
        options:
          required: true
  guides:
    path: "guides"
    output: true
    icon: handshake
    url: "/guides/[relative_base_path]/[slug]/"
    schemas:
      default:
        path: ".cloudcannon/schemas/guide-item.mdx"
      guide_data:
        path: ".cloudcannon/schemas/guide-data.yml"
        _inputs:
          guide_target_ssgs:
            type: "multiselect"
            options:
              values: _select_data.docs_ssgs
              value_key: name
              preview:
                label:
                  key: name
          guide_series:
            type: "select"
            options:
              values: _select_data.docs_guide_series
              value_key: id
              preview:
                label:
                  key: name
  # changelog: {
  #   path: "changelogs",
  #   output: true,
  #   icon: "newspaper",
  #   url: (filePath) => {
  #     const regex =
  #       /^changelogs\/([0-9]{4})\-([0-9]{2})\-([0-9]{2})_(.+)\.mdx?/;
  #     const [, year, month, day, slug] = filePath.match(regex) || [];
  #     return `/changelog/${year}/${month}/${day}/${slug}.html`;
  #   },
  #   parser: "front-matter",
  #   sort: {
  #     key: "path",
  #     order: "desc",
  #   },
  #   create: {
  #     path: "{date|year}-{date|month}-{date|day}_{title|slugify}.[ext]",
  #     _inputs: {
  #       date: {
  #         instance_value: "NOW",
  #       },
  #     },
  #   },
  #   schemas: {
  #     default: {
  #       path: ".cloudcannon/schemas/changelog.mdx",
  #     },
  #   },
  #   _inputs: {
  #     title: {
  #       type: "text",
  #       options: {
  #         required: true,
  #         required_message: "Tell the people what they get",
  #         min_length: 5,
  #         min_length_message: "Tell people a bit more than that"
  #       }
  #     }
  #   }
  # },
  data:
    path: _data
  keys:
    path: _keys
    icon: key
    preview:
      text:
        key: key_name
      metadata:
        - text:
            key: key_value_type
          icon: data_object
        - text:
            key: parent_keys
          icon: escalator_warning
    create:
      path: "[relative_base_path]/{key_name|slugify}.yml"
    schemas:
      default:
        path: ".cloudcannon/schemas/key-definition.yml"
        _inputs:
          key_name:
            type: text
          key_singular_name:
            type: text
          key_value_type:
            type: "multiselect"
            options:
              values: _select_data.key_value_type
              value_key: name
              preview:
                label:
                  key: name
          key_description:
            type: markdown
            options:
              format: "p h1 h2 h3 h4 h5 h6"
              blockquote: true
              bold: true
              italic: true
              strike: true
              subscript: true
              superscript: true
              underline: true
              link: true
              bulletedlist: true
              numberedlist: true
              code: true
              embed: true
              horizontalrule: true
              table: true
              snippet: true
          key_documentation:
            type: object
            comment: "Add a documentation link."
            options:
              subtype: object
              structures:
                values:
                  - label: "Key Documentation Link"
                    comment: "For more information, please read our documentation on..."
                    value:
                      text: null
                      url: null
          parent_keys:
            type: multiselect
            options:
              values: collections.keys
              value_key: key_name
              preview:
                label:
                  key: key_name
          subkeys:
            type: multiselect
            options:
              values: collections.keys
              value_key: key_name
              preview:
                label:
                  key: key_name
  reference:
    path: "_reference"
    icon: "key"
    preview: 
      text: 
        key: key_name
      metadata:
        - text:
            key: full_name
          icon: code
        - text: 
            key: value_type
          icon: data_object
        - text:
            key: child_keys
          icon: escalator_warning
    create:
      path: "[relative_base_path]/{full_name|slugify}.yml"
    schemas:
      default:
        path: ".cloudcannon/schemas/key-reference.yml"
        _inputs:
          name:
            type: text
          full_name:
            type: text
          value_type:
            type: multiselect
            options:
              values: _select_data.key_value_type
              value_key: name
              preview:
                label:
                  key: name
          description:
            type: markdown
            options:
              format: "p h1 h2 h3 h4 h5 h6"
              blockquote: true
              bold: true
              italic: true
              strike: true
              subscript: true
              superscript: true
              underline: true
              link: true
              bulletedlist: true
              numberedlist: true
              code: true
              embed: true
              horizontalrule: true
              table: true
              snippet: true
          examples:
            type: markdown
            options:
              format: "p h1 h2 h3 h4 h5 h6"
              blockquote: true
              bold: true
              italic: true
              strike: true
              subscript: true
              superscript: true
              underline: true
              link: true
              bulletedlist: true
              numberedlist: true
              code: true
              embed: true
              horizontalrule: true
              table: true
              snippet: true
          parent_keys:
            type: multiselect
            options:
              values: collections.reference
              value_key: name
              preview:
                label:
                  key: name
          child_keys:
            type: multiselect
            options:
              values: collections.reference
              value_key: name
              preview:
                label:
                  key: name
  glossary:
    path: _glossary
    icon: abc
    preview:
      text:
        key: key_name
    schemas: 
      default: 
        path: ".cloudcannon/schemas/glossary-term.yml"
        _inputs:
          glossary_term_name:
            type: "text"
          term_description:
            type: "textarea"
            comment: "Keep this as short as possible (i.e., 125 characters)."
            context:
              open: false
              title: "Help"
              icon: "help"
              content: "Try not to use the term name in the description."
            options:
              show_count: true
collection_groups:
  - heading: Users
    collections:
      - articles
      - guides
      - glossary
  - heading: Developers
    collections:
      - keys
      - reference
  - heading: Other
    collections:
      - changelog
      - pages
  - heading: Data
    collections:
      - data
      - common_content

_editables:
  content:
    format: "p h1 h2 h3 h4 h5 h6"
    blockquote: true
    bold: true
    italic: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    link: true
    bulletedlist: true
    numberedlist: true
    code: true
    embed: true
    horizontalrule: true
    table: true
    snippet: true

_structures:
  related_links:
    values:
      value:
        name: ""
        url: ""
  common_content_types:
    values: common_content_structures

_inputs:
  _created_at:
    instance_value: "NOW"
  _uuid:
    instance_value: "UUID"
  description:
    options:
      show_count: true
  explicit_canonical:
    type: "url"
    comment: "Optionally reference a different page or URL that this page should set as its canonical URL"
  article_category:
    type: "multichoice"
    comment: "Choose a [Diataxis category](https://diataxis.fr/compass/)."
    context:
      open: false
      title: "Help"
      icon: "help"
      content: "Acquire skill and understand: Explanation \n\n Acquire skill and act: Guide \n\n Apply skill and understand: Reference \n\n Apply skill and act: Instructions"
    options:
      values: _select_data.diataxis_category
      preview:
        icon_color:
          - key: icon_color
  author_notes:
    type: object
    options:
      subtype: object
  docshots_status:
    type: select
    comment: Select whether this article needs Docshots.
    options:
      values: _select_data.docshots_status
      preview:
        icon_color:
          - key: icon_color
  article_topic: 
    type: multiselect
    comment: Select which topics apply to this article.
    options:
      values: data.article_topics

commit_templates:
  - template_string: '{message}'
    _inputs:
      message:
        type: text
        options:
          required: true
timezone: Pacific/Auckland
base_url: documentation