_schema: default
key_name: build.manually_configure_urls
key_singular_name: manually_configure_urls
key_value_type:
  - Boolean
key_description: >-
  This key toggles whether CloudCannon will skip automatic URL detection and
  rely on the URLs specified in your CloudCannon configuration file. This is
  useful for larger Sites.


  Setting this key to `true` will prevent CloudCannon from automatically
  assigning URLs to your files.


  By default, this key is `false` (i.e., CloudCannon will automatically assign
  URLs to your files).
key_documentation:
  text: manually configuring URLs
  url: /documentation/articles/manually-configure-urls/
parent_keys:
subkeys:
