import { blue, bold } from "@std/fmt/colors";

const LOG_PREFIX = blue("[tidy-versions]");

const filepath = "_data/systemversions.json";
const versions = {
  _comment:
    "Do not edit this file, it is autogenerated each build and committed back to the repo.",
  ...JSON.parse(Deno.readTextFileSync(filepath)),
};

(function cleanHugoVersion() {
  versions.go.hugo.list = versions.go.hugo.list.map((v: string) =>
    v.replace(/^v/, "").replace(/\-[^\+]+\+extended/, "")
  );
  versions.go.hugo.default = versions.go.hugo.list[0];
})();

Deno.writeTextFileSync(filepath, JSON.stringify(versions, null, "\t"));
console.log(
  `${LOG_PREFIX} tidied Hugo versions in ${bold(filepath)} (default ${
    bold(versions.go.hugo.default)
  })`,
);
