---
title: General fixes
type: minor
---
This release fixes a few general issues across the app.

**Fixes:**

* Fixed image upload resizing options not working
* Fixed changing from a custom SSL certificate to an autogenerated one
* Fixed permissions to configure hosting authentication
* Fixed adding an existing image on client editor
