_schema: default
key_name: routes
key_singular_name: routes
key_value_type:
  - Array of Objects
key_description: |-
  This key defines...

  The following nested keys are available...

  Values can be one of the following:

  By default, this key... / This key has no default.

  <comp.Example>
    In this example...

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      key:
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
parent_keys:
subkeys:
