_schema: default
key_name: routes
key_singular_name: routes
key_value_type:
  - Array of Objects
key_description: |-
  This key defines any custom redirects for URLs on CloudCannon hosted Sites.

  The following nested keys are available for each entry in the `routes` array:

  * `from` (required)
  * `to` (required)
  * `status`
  * `forced`
  * `substitutions`

  This key has no default.

  <comp.Example>
    In this example, the `routes` array has three redirect rules: two which indicate that content has moved to a different URL, and one to indicate all subpaths of `/app/` are successful.

    <comp.MultiCodeBlock language="JSON" source="routing.json">
      ``````````
      {
        "routes": [
          {
            "from": "/cloudcannon/(.*)",
            "to": "https://cloudcannon.com/$1",
            "status": 302
          },
          {
            "from": "/documentation/articles/choosing-your-ssg/",
            "to": "/documentation/articles/select-your-ssg/",
            "status": 301
          },
          {
            "from": "/app/(.*)",
            "to": "/app/",
            "status": 200
          }
        ]
      }

      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Routing
  url: /documentation/articles/what-is-routing/
parent_keys:
subkeys:
  - routes.to
  - routes.from
  - routes.forced
  - routes.status
  - routes.substitutions
