_schema: default
key_name: collections_config.[*].singular_name
key_value_type:
  - String
key_description: |-
  This key defines the singular noun for your Collection name. CloudCannon uses the singular noun in the *\+ Add* button in the top right of the *Collection browser* when you select the option to add a new file. This is useful if your Collection name is an irregular plural (e.g., "syllabi" or "syllabuses" to syllabus").
  
  By default, CloudCannon removes the `s` character from regular plurals to create a singular noun (e.g., "posts" to "post").

  This key has no default.

  <comp.Example>
    In this example, the *\+ Add* button option to add a Collection file will read "Add Team Member" rather that "Add Team".

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      team:
        singular_name: Team Member
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
