_schema: default
key_name: collections_config.[*].create
key_value_type:
  - Object
key_description: |-
  This key defines the path to which CloudCannon will save new files in a Collection. CloudCannon generates "Create Paths" when you open the *Review changes* modal.

  The following nested keys are available:

  * `path` (required)
  * `extra_data`
  * `publish_to`
  * `_inputs`
  * `_select_data`
  * `_structures`

  This key has no default.

  <comp.Example>
    In this example, CloudCannon will generate a Create Path for new files in the `blog` Collection using the `date` and `title` structured data keys. For example, CloudCannon will generate a create path of `blog/2024-10-31-spooky-getaway.md` for a file with the date 31st October 2024 and the title "Spooky Getaway".

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        create:
          extra_data:
            filename: '{date|year}-{date|month}-{date|day}-{title}'
          path: '[relative_base_path]/{filename|slugify}.[ext]'
        
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Create Paths
  url: /documentation/articles/set-the-path-for-new-files/
parent_keys:
  - collections_config
  - collections_config.[*].schemas
subkeys:
