_schema: default
key_name: collections_config.[*].url
key_value_type:
key_description: >-
  This key defines the output URL for files in a given Collection.
  
  
  Values for this key should begin and end with the `/` character.


  By default, CloudCannon will use the key name of the Collection.


  <comp.Example>
    In this example, the output URL for files in this Collection will be `/travel/` rather than the default `/blog/`.
    
    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    blog:
      url: /travel/
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>


  For more information, please read our documentation on
  [Collections](/documentation/articles/what-is-a-collection/).
documentation_link: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
