_schema: default
key_name: collections_config.[*].add_options.icon
key_value_type:
  - String
key_description: |-
  This key defines...

  The following nested keys are available...

  Values can be one of the following:

  By default, this key... / This key has no default.

  <comp.Example>
    In this example, the *\+ Add* button dropdown in the `team` *Collection browser* has a link to the Office Locations page on our live website.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      team:
        add_options:
          - name: Office Locations
            icon: map
            href: /our-offices
    ``````````
    </comp.MultiCodeBlock>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].add_options
subkeys:
