_schema: default
key_name: collections_config.[*].disable_url
key_singular_name: disable_url
key_value_type:
  - Boolean
key_description: >-
  This key toggles whether CloudCannon will generate an output URL for a given
  Collection.


  Setting this key to `true` will prevent CloudCannon from generating an output
  URL for a Collection.


  By default, this key is `false` (i.e., generate an output URL for this
  Collection).


  <comp.Example>
    In this example, `data` is an non-output Collection and we don't want output URLs generated.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        data:
          disable_url: true
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
