_schema: default
key_name: collections_config.[*].documentation.text
key_value_type:
  - String
key_description: >-
  This key defines the link text for the documentation link at the top of a
  *Collection browser*.


  By default, this key is `Documentation`.


  <comp.Example>
    In this example, the text for the documentation link is `CloudCannon Documentation`.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      data:
        documentation:
          url: https://cloudcannon.com/documentation/
          text: CloudCannon Documentation
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
documentation_link:
parent_keys:
  - collections_config.[*].documentation
subkeys:
