_schema: default
key_name: collections_config.[*].path
key_value_type:
  - String
key_description: >-
  This key defines the folder path for the collection key in which it is nested.


  The value for this key is relative to your [Site
  source](/documentation/articles/configuration-file-reference/#source). Each
  Collection must have a unique path.


  This key has no default.


  <comp.Example>
    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        path: content/blog
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>


  For more information, please read our documentation on
  [Collections](/documentation/articles/what-is-a-collection/).
documentation_link: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
