_schema: default
key_name: collections_config.[*].path
key_value_type:
  - String
key_description: >-
  This key defines the folder path for the collection key in which it is nested.


  The value for this key is relative to your [Site
  source](/documentation/articles/configuration-file-reference/#source). Each
  Collection must have a unique path.


  This key has no default.


  <comp.Example>
    In this example, the files for the `blog` Collection are located in the `content/blog` folder.
  
    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        path: content/blog
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
