_schema: default
key_name: collections_config.[*].add_options.schema
key_value_type:
  - String
key_description: |-
  This key defines which Schema CloudCannon should use to populate a file created with an option in the *\+ Add* button dropdown. This Schema is relative to the Collection configured in `add_options.collection`.
  
  The value for this key should be the key name of a Schema.
  
  By default, this key is the default Schema in the Collection configured in `add_options.collection`.

  <comp.Example>
    In this example, we want CloudCannon to populate new files with the contents of the `articles` Schema when a team member selects this option from the + Add button dropdown.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      articles:
        add_options:
          - name: Add articles
            collection: new_articles
            schema: articles
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].add_options
subkeys:
