_schema: default
key_name: collections_config.[*].name
key_value_type:
  - String
key_description: >-
  This key defines the display name for a Collection. The name appears in the
  *Site Navigation* and at the top of the *Collection browser*. Changing the
  display name does not affect the Collection key name.


  By default, CloudCannon uses the Collection key name in title case (i.e.,
  `blog_files` becomes "Blog Files").


  <comp.Example>
    In this example, CloudCannon will call the `blog` Collection "Travel Blog" in the *Site Navigation* and the *Collection browser*.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        name: Travel Blog
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
documentation_link:
parent_keys:
  - collections_config
subkeys:
