_schema: default
key_name: collections_config.[*].add_options.icon
key_singular_name: icon
key_value_type:
  - String
key_description: >-
  This key defines the icon for an option in the *\+ Add* button dropdown.


  Values can be from <a
  href="https://fonts.google.com/icons?icon.set=Material+Icons" target="_blank"
  rel="noopener">Google's Material Icons</a> library.


  By default, this key is `add`, unless you have configured
  `add_options.schema`. In this case, this key defaults to the icon of the
  matching Schema.


  <comp.Example>
    In this example, the *\+ Add* button dropdown in the `team` *Collection browser* has a link to the Office Locations page on our live website.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        team:
          add_options:
            - name: Office Locations
              icon: map
              href: /our-offices
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].add_options
subkeys:
