_schema: default
key_name: collections_config.[*].sort_options.key
key_value_type:
  - String
key_description: |-
  This key defines...

  The following nested keys are available...

  Values can be one of the following:

  By default, this key... / This key has no default.

  <comp.Example>
    In this example, the *Sort* dropdown in the `blog` *Collection browser* has ascending and descending options for sorting by `author` and `date`.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
        ``````````
        collections_config:
          blog:
            sort_options:
              - key: author
                order: ascending
                label: Author (A-Z)
              - key: author
                order: descending
                label: Author (Z-A)
              - key: date
                order: ascending
                label: Date (Newest First)
              - key: date
                order: descending
                label: Date (Oldest First)
        ``````````
        </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].sort_options
subkeys:
