_schema: default
key_name: collections_config.[*].disable_file_actions
key_singular_name: disable_file_actions
key_value_type:
  - Boolean
key_description: >-
  This key toggles whether team members can use the  *Move*, *Clone*, *Rename*,
  and *Delete* file actions in a Collections. You can access these file actions
  in the *Context menu* at the top right of a file
  [Card](/documentation/articles/configure-your-card-previews/) in the
  *Collection browser* or in an editing interface. This key does not affect file
  actions in the *File browser*.


  Setting this key to `true` will prevent team members from using file actions
  in the *Collection browser*.


  By default, this key is `false` (i.e., team members can use file actions) for
  most SSGs. For Eleventy, Hugo, and Jekyll, this key defaults to `true` for the
  `data` Collection.


  <comp.Example>
    In this example, we want to prevent team members from using file actions in the `data` Collection through the *Collection browser*.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
        ``````````
        collections_config:
          data:
            disable_file_actions: true
        ``````````
        </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
