_schema: default
key_name: collections_config.[*].glob
key_value_type:
  - Array of Strings
key_description: >-
  This key defines globs which filter the files visible in the *Collection
  browser* for a given Collection. Values in this array are relative to the
  Collection [path](/documentation/articles/collections-reference/#path).


  Globs can be positive (e.g. `*.yml`), or negative (e.g. `!**/*.json`). Files
  are included in a Collection if they match any positive globs and do not match
  any negative globs. If you do not define any positive globs, CloudCannon will
  include all non-developer files in a Collection unless they match a negative
  glob.


  <comp.Notice info_type="info">
    For more information about developer files, please read our documentation on the [include\_developer\_files](/documentation/articles/collections-reference/#include_developer_files) key.
  </comp.Notice>


  Defining a negative glob for a Collection does not remove a file from the
  associated Collection folder in your Git repository. Similarly, defining a
  positive glob for a file in a folder outside your Collection path does not
  move the file.


  This key has no default.


  <comp.Example>
    In this example, the *Collection browser* will show all files in the `data` folder except for the `secret.yml` file:

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      data:
        path: data
        glob:
          - '!secret.yml'
    ``````````
    </comp.MultiCodeBlock>

    In this example, the *Collection browser* will show only `.yml` files in the `data` folder or any nested folders:

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      data:
        path: data
        glob:
          - '**/*.yml'
    ``````````
    </comp.MultiCodeBlock>

    In this example, the *Collection browser* will show only `.yml` files in the `data` folder, except for the `secret.yml` file:

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      data:
        path: data
        glob:
          - '**/*.yml'
          - '!secret.yml'
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>


  For more information, please read our documentation on
  [Collections](/documentation/articles/what-is-a-collection/).
documentation_link: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
