_schema: default
key_name: collections_config.[*].add_options.name
key_singular_name: name
key_value_type:
  - String
key_description: >-
  This key defines the name of an option in the *\+ Add* button dropdown.


  This key has no default, unless you have configured `add_options.schema`. In
  this case, this key defaults to the name of the matching Schema.


  <comp.Example>
    In this example, the *\+ Add* button dropdown in the `team` *Collection browser* has a link to the Office Locations page on our live website.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        team:
          add_options:
            - name: Office Locations
              icon: map
              href: /our-offices
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].add_options
subkeys:
