_schema: default
key_name: collections_config.[*].add_options
key_value_type:
  - Array of Objects
key_description: >-
  This key defines the options available in the *\+ Add* button dropdown at the
  top right of your *Collection browser.*


  The following nested keys are available for each standard entry in
  `add_options`:


  * `name`

  * `icon`

  * `editor`

  * `base_path`

  * `collection`

  * `schema`

  * `default_content_file`


  The following nested keys are available for each URL entry in `add_options`:


  * `name`

  * `icon`

  * `href`


  By default, CloudCannon adds the "Add a file" and "Create new folder" options
  to the *\+ Add* dropdown. Additionally, any Schemas you have configured for a
  Collection will also appear in the *\+ Add* dropdown. For more information on
  these options, please read our reference documentation on
  [disable\_add](/documentation/articles/collections-reference/#disable_add),
  [disable\_add\_folder](/documentation/articles/collections-reference/#disable_add_folder),
  and [schemas](/documentation/articles/schemas-reference/#schemas).


  <comp.Example>
    In this example, we have configure two extra options for the *\+ Add* button dropdown in the `blog` *Collection browser*.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        add_options:
          - name:
            icon:
            editor:
            base_path:
            collection:
            schema:
            default_content_file:
          - name:
            icon:
            href:
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
