_schema: default
key_name: collections_config.[*].sort_options
key_singular_name: sort_options
key_value_type:
  - Array of Objects
key_description: >-
  This key defines the options for the *Sort* dropdown in a *Collection
  browser*. Configuring sort options for a Collection will remove CloudCannon's
  default sorting options from the *Sort* dropdown.


  The following nested keys are available for each entry in the `sort_options`
  array:


  * `key` (required)

  * `order`

  * `label`


  By default, CloudCannon provides sorting options for path, file size, file
  creation time, and last modified, in ascending and descending order.
  CloudCannon will also read data keys from your early Collection files and
  provide options to sort by those key values.


  <comp.Example>
    In this example, the *Sort* dropdown in the `blog` *Collection browser* only contains options for sorting by `author` and `date` in ascending and descending order.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
        ``````````
        collections_config:
          blog:
            sort_options:
              - key: author
                order: ascending
                label: Author (A-Z)
              - key: author
                order: descending
                label: Author (Z-A)
              - key: date
                order: ascending
                label: Date (Newest First)
              - key: date
                order: descending
                label: Date (Oldest First)
        ``````````
        </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
  - collections_config.[*].sort_options.key
  - collections_config.[*].sort_options.label
  - collections_config.[*].sort_options.order
