_schema: default
key_name: collections_config.[*].documentation.url
key_value_type:
  - String
key_description: >-
  This key defines the URL for the documentation link at the top of a
  *Collection browser*. You must define this key for the
  `documentation` object to function.


  This key has no default.


  <comp.Example>
    In this example, we have configured the `blog` Collection documentation link to go to `example.com`.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        documentation:
          url: https://example.com
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
documentation_link:
parent_keys:
  - collections_config.[*].documentation
subkeys:
