_schema: default
key_name: collections_config.[*].add_options.collection
key_singular_name: collection
key_value_type:
  - String
key_description: >-
  This key defines the Collection for files created using an option in the *\+
  Add* button dropdown. This Collections overrides the current Collection open
  in the *Collection browser*.


  The value for this key should be the key name of a Collection.


  By default, this key is the current Collection open in the *Collection
  browser*.


  <comp.Example>
    In this example, we want team members in the articles Collection to create new files in the `new_articles` Collection rather than the current Collection browser they have open. By configuring the `collection` value to `new_articles`, new files will be created in a different Collection (i.e., `new_articles`) when a team member selects this option from the + Add button dropdown.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        articles:
          add_options:
            - name: Add articles
              collection: new_articles
              schema: articles
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].add_options
subkeys:
