_schema: default
key_name: collections_config.[*].sort.key
key_value_type:
  - String
key_description: |-
  This key defines which key CloudCannon should use to sort files in your *Collection browser*. You must define this key for the `sort` object to function.

  Value must be the name of a structured data key in your Collection files.

  This key has no default.

  <comp.Example>
    In this example, CloudCannon will sort files in the `blog` Collection by the `date` key in the frontmatter of each file, in ascending order.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        blog:
          sort:
            key: date
            order: ascending
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].sort
subkeys:
