_schema: default
key_name: collections_config.[*].url
key_singular_name: url
key_value_type:
  - String
key_description: >-
  This key defines the output URL for files in a given Collection. CloudCannon
  uses the output URL in the [Visual
  Editor](/documentation/articles/the-visual-editor/), and on your [Testing
  Domain](/documentation/articles/testing-domain/) and
  [Custom
  Domain](/documentation/articles/what-is-a-custom-domain/).


  Values for this key can be a mix of plain text and template strings, and
  should begin and end with the `/` character. Template strings can contain data
  placholders and fixed placeholders, which CloudCannon will replace with the
  data it references when generating the output URL.


  <comp.Notice info_type="info">
    For more information about data placeholders and fixed placeholders, please read our documentation on [configuring your template strings](/documentation/articles/configure-your-template-strings/).
  </comp.Notice>


  By default, CloudCannon will use the key name of the Collection.


  <comp.Example>
    In this example, the output URL for files in this Collection will be `/travel/` rather than the default `/blog/`.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
        ``````````
        collections_config:
          blog:
            url: /travel/[slug]/
        ``````````
        </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
