_schema: default
key_name: collections_config.[*].add_options.default_content_file
key_value_type:
  - String
key_description: |-
  This key defines which file CloudCannon should use to populate a file created with an option in the *\+ Add* button dropdown if the Collection defined in `add_options.collection` has no Schemas configured. The `add_options.schema` key will override `default_content_file`.

  This key has no default.

  <comp.Example>
    In this example, we want CloudCannon to populate the initial contents of new files with `event_template.yml`.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      events:
        add_options:
          name: Add new event
          collection: upcoming_events
          default_content_file: event_template.yml
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].add_options
subkeys:
