_schema: default
key_name: collections_config.[*].add_options.editor
key_singular_name: editor
key_value_type:
  - String
key_description: >-
  This key defines which editing interface CloudCannon will use when you select
  an option from the *\+ Add* button dropdown.


  Values can be one of the following: `visual`, `content`, or `data`.


  By default, CloudCannon will open the new file in an appropriate editing
  interface for that file type. If CloudCannon cannot determine an appropriate
  editing interface, it will show a warning.


  <comp.Example>
    In this example, we want new draft blog files to open in the [Content Editor](/documentation/articles/the-content-editor/).

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
          _posts:
            add_options:
              - name: Add draft blog
                icon: post_add
                editor: content
                base_path: /../_drafts/blog

      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].add_options
subkeys:
