_schema: default
key_name: collections_config.[*].include_developer_files
key_value_type:
  - Boolean
key_description: >-
  This key toggles whether CloudCannon removes developer files from your
  *Collection browser*. CloudCannon excludes files that probably shouldn't be edited in a CMS from your *Collection browser*, for example files like `README.md` or `package.json`. CloudCannon excludes these files even if you have configured globs to allow them.


  Setting this key to `true` will allow CloudCannon to show developer files,
  assuming they are not filtered out by any configured
  [globs](/documentation/articles/collections-reference#glob).


  By default, this key is `false` (i.e., do not include developer files).


  <comp.Example>
    In this example...

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      data:
        include_developer_files: true
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>


  For more information, please read our documentation on
  [Collections](/documentation/articles/what-is-a-collection/).
documentation_link: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
