_schema: default
key_name: collections_config.[*].schema_key
key_value_type:
  - String
key_description: |-
  This key defines the name for the structured data key that references the Schema a file uses. CloudCannon automatically adds this key to the top of your file when you create it using a Schema.
  
  Values which beginning with the `_` character are hidden from the Data Editor and the sidebar of the Content and Visual Editors.

  By default, this key is `_schema`.

  <comp.Example>
    In this example, we want to make Schemas more friendly for our non-technical team members, so we have configured the schema key in the front matter of files in the `blog` Collection to be `blog_template`.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        schema_key: _blog_template
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Schemas
  url: /documentation/articles/what-is-a-schema/
parent_keys:
  - collections_config
subkeys:
