_schema: default
key_name: collections_config.[*].disable_add
key_singular_name: disable_add
key_value_type:
  - Boolean
key_description: >-
  This key toggles whether team members can use the *\+ Add* button in the top
  right of the *Collection browser* to add files to a Collection. This key does
  not affect your ability to add files using the *File browser*.


  Setting this key to `true` will prevent team members from adding new files
  through the *Collection browser*.


  By default, this key is `false` (i.e., team members can add to the Collection)
  for most SSGs. For Eleventy, Hugo, and Jekyll, this key defaults to `true` for
  the `data` Collection (all subfolders in the `data` folder are non-output
  Collections).


  If both `disable_add` and`disable_add_folder` are set to `true`, and you have
  not defined any other `add_options`, then the *\+ Add* button will not appear
  in the top right of the *Collection browser*.


  <comp.Example>
    In this example, we want to prevent team members from adding new files to the `data` Collection through the *Collection browser*.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
        ``````````
        collections_config:
          data:
            disable_add: true
        ``````````
        </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
subkeys:
