_schema: default
key_name: collections_config.[*].documentation.icon
key_value_type:
  - String
key_description: >-
  This key defines the icon for the documentation link at the top of a
  *Collection browser*.


  Values can be from [Google's Material
  Icons](https://fonts.google.com/icons?icon.set=Material+Icons) library.


  By default, this key is `auto_stories`.


  <comp.Example>
    In this example, we have configured the `star` icon for the `blog` Collection documentation link.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
        ``````````
        collections_config:
          blog:
            documentation:
              url: https://www.cloudcannon.com/documentation/
              icon: star
        ``````````
        </comp.MultiCodeBlock>
  </comp.Example>


  For more information, please read our documentation on
  [Collections](/documentation/articles/what-is-a-collection/).
documentation_link: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].documentation
subkeys:
