_schema: default
key_name: collections_config.[*].sort_options.label
key_value_type:
  - String
key_description: >-
  This key defines the label used for a file sorting option in the *Sort*
  dropdown.


  This key has no default.


  <comp.Example>
    In this example, the sorting method which uses the `author` key is called "Author (A-Z)" in the *Sort* dropdown.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        sort_options:
          - key: author
            order: ascending
            label: Author (A-Z)
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].sort_options
subkeys:
