_schema: default
key_name: collections_config.[*].new_preview_url
key_singular_name: new_preview_url
key_value_type:
  - String
key_description: >-
  This key defines a new URL for previewing your unbuilt pages in the [Visual
  Editor](/documentation/articles/the-visual-editor/). The Visual Editor will
  load the new preview URL and use Data Bindings and Previews to render your
  page without saving or building.


  This key does not affect the URL for your [Testing
  Domain](/documentation/articles/what-is-a-testing-domain/) or
  [Custom
  Domain](/documentation/articles/what-is-a-custom-domain/).


  This key has no default.


  <comp.Example>
    In this example, the Visual Editor will open the `/about/` page when you open an unbuilt page from the `blog` Collection.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        blog:
          new_preview_url: /about/
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
