_schema: default
key_name: collections_config.[*].add_options.base_path
key_value_type:
  - String
key_description: |-
  This key defines a path for files created using an option in the *\+ Add* button dropdown. This path overrides the path for the current Collection and subfolder open in the *Collection browser*. This key is useful if you need to specify a specific subfolder within a Collection.
  
  The value for this key is relative to your Collection [path](/documentation/articles/collections-reference/#path).

  By default, this key is the path for the current Collection and subfolder open in the *Collection browser*.

  <comp.Example>
    In this example, we want team members in the `_posts` Collection to create new files in the`blog` subfolder of the `_drafts` Collection rather than the current *Collection browser* they have open. By configuring the `base_path` value to `/../_drafts/blog`, new files will be created in a different Collection subfolder (i.e., `_drafts`) when a team member selects this option from the *\+ Add* button dropdown.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
        _posts:
          add_options:
            - name: Add draft blog
              icon: post_add
              editor: content
              base_path: /../_drafts/blog
              
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].add_options
subkeys:
