_schema: default
key_name: collections_config.[*].icon
key_value_type:
  - String
key_description: >-
  This key defines the icon for a Collections. Collection icons appear in the
  *Site Navigation* and are the default icon for Collection file [Cards](/documentation/articles/configure-your-card-previews/) if you
  have not defined `preview.icon`.
  

  <comp.Notice info_type="info">
    For more information about the preview icon, please read our documentation on the [preview](/documentation/articles/configure-your-card-previews/) key.
  </comp.Notice>


  Values can be from [Google's Material
  Icons](https://fonts.google.com/icons?icon.set=Material+Icons) library.


  By default, CloudCannon uses the Material Icon with the closest name to your
  Collection key name.


  <comp.Example>
    In this example, we have configured the `post_add` icon for the `blog` Collection.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        icon: post_add
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>


  For more information, please read our documentation on
  [Collections](/documentation/articles/what-is-a-collection/).
documentation_link: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
