_schema: default
key_name: collections_config.[*].add_options.schema
key_value_type:
  - String
key_description: |-
  This key defines...

  The following nested keys are available...

  Values can be one of the following:

  By default, this key... / This key has no default.

  <comp.Example>
    In this example...

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
                ``````````
                key:
                ``````````
                </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].add_options
subkeys:
