_schema: default
key_name: collections_config.[*].sort_options.order
key_value_type:
  - String
key_description: >-
  This key defines which order an option in the *Sort* dropdown should use to
  sort files in your *Collection browser*. CloudCannon will sort files according
  to the value of `sort_options.key` for each option in the *Sort* dropdown.


  Values can be one of the following: `asc`, `ascending`, `desc`, or
  `descending`.


  By default, this key is `ascending`.


  <comp.Example>
    In this example, the "Author (A-Z)" option in the *Sort* dropdown will sort files in the `blog` *Collection browser* in ascending order.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    collections_config:
      blog:
        sort_options:
          - key: author
            order: ascending
            label: Author (A-Z)
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config.[*].sort_options
subkeys:
