_schema: default
key_name: collections_config.[*].description
key_singular_name: description
key_value_type:
  - String
key_description: >-
  This key defines the description text that appears on the *Collection browser*
  page. Collection descriptions are useful for adding extra context for your
  team members.


  CloudCannon supports a limited selection of Markdown formatting for the value
  of this key: links, bold, italic, subscript, superscript, and inline code.


  This key has no default.


  <comp.Example>
    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        blog:
          description:|-
            This Collection is for *Travel blogs* and *Customer stories*.

            If your have any questions, please contact Heather.
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
