_schema: default
key_name: collections_config
key_value_type:
  - Array of Objects
key_description: >-
  This key defines your Collections. The following nested keys are available for
  each Collection:


  * `path`

  * `glob`

  * `name`

  * `singular_name`

  * `icon`

  * `url`

  * `disable_url`

  * `documentation`

  * `description`

  * `preview`

  * `sort`

  * `sort_options`

  * `_editables`

  * `_enabled_editors`

  * `_inputs`

  * `_select_data`

  * `_structures`

  * `add_options`

  * `create`

  * `disable_add`

  * `disable_add_folder`

  * `disable_file_actions`

  * `new_preview_url`

  * `schemas`

  * `schema_key`

  * `include_developer_files`


  By default, CloudCannon uses your `source` key to make assumptions about your
  Collections.


  <comp.Example>
    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        blog:
          path: content/blog
          glob:
          name: Blog
          singular_name:
          icon: post_add
          url:
          disable_url: false
          documentation:
          description: ''
          preview:
          sort:
          sort_options:
          _editables:
          _enabled_editors:
          _inputs:
          _select_data:
          _structures:
          add_options:
          create:
          disable_add: false
          disable_add_folder: false
          disable_file_actions: false
          new_preview_url:
          schemas:
            post:
              path: schemas/post.md
              reorder_inputs: true
              hide_extra_inputs: false
              remove_empty_inputs: false
              remove_extra_inputs: true
              name: Blog Post
              icon: post_add
            customer_story:
              path: schemas/customer-story.md
              reorder_inputs: true
              hide_extra_inputs: false
              remove_empty_inputs: false
              remove_extra_inputs: true
              icon: auto_stories
          schema_key:
          include_developer_files:
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>


  For more information, please read our documentation on
  [Collections](/documentation/articles/what-is-a-collection/).
documentation_link: /documentation/articles/what-is-a-collection/
parent_keys:
subkeys:
