_schema: default
key_name: collections_config.[*].documentation
key_singular_name: documentation
key_value_type:
  - Object
key_description: >-
  This key defines the documentation link at the top of a *Collection browser*.
  Collection documentation is useful for assisting your team members.


  The following nested keys are available:


  * `url` (required)

  * `text`

  * `icon`


  This key has no default.


  <comp.Example>
    In this example, the documentation link for the `data` Collection goes to [CloudCannon Documentation](https://cloudcannon.com/documentation/).

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        data:
          documentation:
            url: https://www.cloudcannon.com/documentation/
            text: CloudCannon Documentation
            icon: star
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
child_keys:
  - collections_config.[*].documentation.url
  - collections_config.[*].documentation.icon
  - collections_config.[*].documentation.text
