_schema: default
key_name: collections_config.[*].add_options
key_singular_name: add_options
key_value_type:
  - Array of Objects
key_description: >-
  This key defines the options available in the *\+ Add* button dropdown at the
  top right of your *Collection browser*. This key defines the options available
  in the *\+ Add* button dropdown at the top right of your *Collection browser*.
  Configuring add options for a Collection will remove CloudCannon's default
  "Add a file" option from the *\+ Add* button dropdown.


  The following nested keys are available for each standard entry in
  `add_options`:


  * `name`

  * `icon`

  * `editor`

  * `base_path`

  * `collection`

  * `schema`

  * `default_content_file`


  The following nested keys are available for each URL entry in `add_options`:


  * `name`

  * `icon`

  * `href`


  By default, CloudCannon adds the "Add a file" and "Create new folder" options
  to the *\+ Add* dropdown. Additionally, any Schemas you have configured for a
  Collection will also appear in the *\+ Add* dropdown. For more information on
  these options, please read our reference documentation on
  [disable\_add](/documentation/articles/collections-reference/#disable_add),
  [disable\_add\_folder](/documentation/articles/collections-reference/#disable_add_folder),
  and [schemas](/documentation/articles/schemas-reference/#schemas).


  <comp.Example>
    In this example, we want team members in the `_posts` Collection to create new files in the`blog` subfolder of the `_drafts` Collection. CloudCannon will open these files in the [Content Editor](/documentation/articles/the-content-editor/).

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
          _posts:
            add_options:
              - name: Add draft blog
                icon: post_add
                editor: content
                base_path: /../_drafts/blog

      ``````````
      </comp.MultiCodeBlock>

    In this example, the *\+ Add* button dropdown in the `team` *Collection browser* has a link to the Office Locations page on our live website.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
      ``````````
      collections_config:
        team:
          add_options:
            - name: Office Locations
              icon: map
              href: /our-offices
      ``````````
      </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Collections
  url: /documentation/articles/what-is-a-collection/
parent_keys:
  - collections_config
subkeys:
  - collections_config.[*].add_options.href
  - collections_config.[*].add_options.icon
  - collections_config.[*].add_options.name
  - collections_config.[*].add_options.editor
  - collections_config.[*].add_options.schema
  - collections_config.[*].add_options.base_path
  - collections_config.[*].add_options.collection
  - collections_config.[*].add_options.default_content_file
