_schema: default
key_name: data_config.[*].path
key_value_type:
  - String
key_description: >-
  This key defines the file or folder path for the data key in which it is
  nested.


  This key has no default.


  For more information, please read our documentation on [defining your
  data](/documentation/articles/define-your-data/).
documentation_link: /documentation/articles/define-your-data/
parent_keys:
  - data_config
subkeys:
