_schema: default
key_name: file_config
key_value_type:
  - Array
key_description: >-
  This key defines file-specific configuration without configuring a collection
  or modifying files.


  The following nested keys are available for each entry in `file_config`:


  * `glob` (required)

  * `_select_data`

  * `_structures`

  * `_select_data`

  * `_enabled_editors`

  * `_inputs`

  * `_editables`


  This key has no default.


  For more information, please read our documentation on .
documentation_link:
parent_keys:
subkeys:
