_schema: default
key_name: _inputs.[*].options.values
key_value_type:
  - Array
  - Object
  - String
key_description: >-
  This key defines which values are available for a Select or Multiselect input.
  You must define this key for the Select or Multiselect input to function.


  Value can be an array of options, or a string referencing a fixed data set,
  Collection, or data file.


  This key has no default.


  <comp.Example>
    In this example, CloudCannon will provide items in the `posts` Collection as values for the `heathers_posts` input. CloudCannon will also apply a filter, returning only files where the `author` structured data key is equal to "Heather".

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    _inputs:
      heathers_posts:
        type: multiselect
        label: Heather's Posts
        options:
          values: "collections.posts[?(@.author == 'Heather')]"
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Select and Multiselect inputs
  url: /documentation/articles/select-and-multiselect-inputs/
parent_keys:
  - _inputs.[*].options
subkeys:
