_schema: default
key_name: _structures.[*].values.tags
key_singular_name: tags
key_value_type:
  - Array of Strings
key_description: |-
  This key defines which tags are associated with a given value in a Structure. You can use tags to group and filter Structure options when selecting from a modal. The `style` key must be set to `modal` for this key to function.
  
  This key has no default.

  <comp.Example>
    In this example we have three options for the `page_components` Structure: `Hero Component`, `Feature Component`, and `Video Component`. We can search the Structure modal using the `image`, `text`, `button`, and `video` tags to filter Structure values.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    _structures:
      page_components:
        style: modal
        values:
          - label: Hero Component
            tags:
              - image
              - text
            value:
              title: 
              description: 
              image_path: 
              link:
                text: 
                url: 
          - label: Feature Component
            tags:
              - image
              - text
              - button
            value:
              image_path: 
              title: 
              description: 
              button:
                link: 
                text: 
              reversed_layout: false
          - label: Video Component
            tags:
              - image
              - video
            value:
              image_path: 
              videoUrl:
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Structures
  url: /documentation/articles/what-is-a-structure/
parent_keys:
  - _structures.[*].values
subkeys:
