_schema: default
key_name: _structures.[*].values.groups
key_singular_name: groups
key_value_type:
  - Array of Objects
key_description: >-
  This key defines the order and customing grouping for inputs within a
  Structure. Each groups can have a heading.


  The following nested keys are available for each entry in the `groups` array:


  * `heading`

  * `inputs`


  By default, CloudCannon respects the order of inputs as configured in the
  `values.value` key and does not include any groups.


  <comp.Example>
    In this example, we want to separate the inputs into two groups with descriptive headings: `title` and `subtitle` under the `Titles` heading, and `author` under the `Details` heading.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    _structures:
      article_information:
        values:
          - label: Blog
            value:
              title:
              subtitle:
              author:
            groups:
              - heading: Titles
                inputs:
                  - title
                  - subtitle
              - heading: Details
                inputs:
                  - author
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Structures
  url: /documentation/articles/what-is-a-structure/
parent_keys:
  - _structures.[*].values
subkeys:
