_schema: default
key_name: _structures.[*].values.label
key_singular_name: label
key_value_type:
  - String
key_description: |-
  This key defines the dispaly name for a given value in a Structure. The name will appear in the */+ Add* button dropdown below an Object or Array input or in the Structures modal (if configured).

  By default, this key falls back to `unknown`.

  <comp.Example>
    In this example, we want two value options for our `staff` structure: one called `Manager` and one called `Employee`.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    _structures:
      staff:
        values:
          - label: Employee
            value:
              name:
              job_description:
              profile_picture:
          - label: Manager
            value:
              name:
              job_description:
              profile_picture:
              url:
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Structures
  url: /documentation/articles/what-is-a-structure/
parent_keys:
  - _structures.[*].values
subkeys:
