_schema: default
key_name: _structure.[*].values.tabbed
key_singular_name: tabbed
key_value_type:
  - Boolean
key_description: >-
  This key toggles whether CloudCannon should create tabs in the Data Editor if you have two layers of nested object within your Structure.
  
  <comp.Notice info_type="info"> CloudCannon would create tabs automatically for Non-unified Configuration Sites, but it must be explicitly configured in the Unified Configuration file format. </comp.Notice>
  
  By default, this key is `false` (i.e., Object and Array inputs using this Structure option are not tabbed).
  
  <comp.Example>
    In this example, we want the `content` and `style` keys in our Structure to be tabs at the top of the Data Editor, with the `title` and `text`, and `color` and `font` keys nested within those tabs respectively.
    
    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    _structures:
      components:
        values:
          - label: Component
            tabbed: true
            value:
              content:
                title:
                text:
              style:
                color:
                font:
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Structures
  url: /documentation/articles/what-is-a-structure/
parent_keys:
  - _structures.[*].values
subkeys:
