_schema: default
key_name: _structures.[*].values
key_singular_name: values
key_value_type:
  - Array of Objects
key_description: >-
  This key defines the options available for a Structure. You must define this key for the Structure to function.

  The following nested keys are available for each entry in the `values` array:

  * `id`
  * `default`
  * `tabbed`
  * `_inputs`
  * `tags`
  * `value` (required)
  * `groups`
  * `label`
  * `picker_preview`
  * `preview`

  This key has no default.

  <comp.Example>
    In this example, we want to add the `title`, `subtitle`, `author`, `featured_image`, and `url` fields to Object or Array inputs that reference this Structure.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    _structures:
      related_articles:
        values:
          - label: Blog
            id:
            default: true
            tabbed: false
            tags:
              - blog
            value:
              title:
              subtitle:
              author:
              featured_image:
              url:
            _inputs:
              featured_image:
                type: image
                options:
                  width: 50
                  height: 50
            groups:
              - heading: Titles
                inputs:
                  - title
                  - subtitle
              - heading: Details
                inputs:
                  - author
                  - image
                  - url
            preview:
              text:
                - template: "{title}"
              subtext:
                - template: "By {author}"
              image:
                - key: image
            picker_preview:
              text: Blog
              subtext: Add a related blog
              icon: post_add
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Structures
  url: /documentation/articles/what-is-a-structure/
parent_keys:
  - _structures
subkeys:
  - _structures.[*].values.id
  - _structures.[*].values.tags
  - _structures.[*].values.label
  - _structures.[*].values.value
  - _structures.[*].values.default
  - preview
  - picker_preview
  - _structure.[*].values.tabbed
  - _structures.[*].values.groups
