_schema: default
key_name: _structures.[*].values.default
key_singular_name: default
key_value_type:
  - Boolean
key_description: >-
  This key toggles whether CloudCannon should treat an entry in the `values`
  array as the default option for your Object or Array input. If multiple
  entries in the `values` array are set to `true`, CloudCannon will use the
  first entry.


  If CloudCannon cannot determine the type of an entry within the `values` array
  based on the `id_key` or matching inputs in the `values.value` array, it will
  fall back to the default entry.


  By default, this key is `false` (i.e., the entry is not the default option).


  <comp.Example>
    In this example, we want the entry labelled `Employee` to be our default option for populating inputs configured with the `staff` Structure.

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    _structures:
      staff:
        style: modal
        values:
          - label: Employee
            default: true
            value:
              name:
              job_description:
              profile_picture:
          - label: Manager
            value:
              name:
              job_description:
              profile_picture:
              url:
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Structures
  url: /documentation/articles/what-is-a-structure/
parent_keys:
  - _structures.[*].values
subkeys:
