_schema: default
key_name: _structures.[*].values.id
key_singular_name: id
key_value_type:
  - String
key_description: |-
  This key defines the string used to identify a given Structure value when refering to it from other input configuration.
  
  This key has no default.

  <comp.Example>
    In this example...

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    key:
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Structures
  url: /documentation/articles/what-is-a-structure/
parent_keys:
  - _structures.[*].values
subkeys:
