_schema: default
key_name: _structures.[*].values
key_singular_name: values
key_value_type:
  - Array of Objects
key_description: |-
  This key defines the options available for a Structure. You must define this key for the Structure to function.

  The following nested keys are available for each entry in the `value` array:

  * `id`
  * `icon`
  * `tags`
  * `image`
  * `label`
  * `value` (required)
  * `default`
  * `preview`
  * `picker_preview`

  This key has no default.

  <comp.Example>
    In this example...

    <comp.MultiCodeBlock language="YAML" translate_into={["json"]} source="cloudcannon.config.yml">
    ``````````
    _structures:
      test:
        values:
          - id:
            default:
            icon:
            image:
            label:
            picker_preview:
            preview:
            tags:
              - blog
            value:
              name:
              description:
              url:
    ``````````
    </comp.MultiCodeBlock>
  </comp.Example>
key_documentation:
  text: Structures
  url: /documentation/articles/what-is-a-structure/
parent_keys:
  - _structures
subkeys:
  - _structures.[*].values.id
  - _structures.[*].values.icon
  - _structures.[*].values.tags
  - _structures.[*].values.image
  - _structures.[*].values.label
  - _structures.[*].values.value
  - _structures.[*].values.default
  - _structures.[*].values.preview
  - _structures.[*].values.picker_preview
