_schema: default
key_name: collections_config
key_value_type:
  - Object
key_description: >-
  This key defines your Collections. Each Collection is a group of related files
  with a similar format (e.g., a folder of pages, blog posts, or data files). In
  CloudCannon, your collections appear in the *App Navigation* for easy access.


  The following nested keys are available:


  * `[*].path`

  * `[*].glob`

  * `[*].name`

  * `[*].singular_name`

  * `[*].icon`

  * `[*].url`

  * `[*].disable_url`

  * `[*].documentation`

  * `[*].description`

  * `[*].preview`

  * `[*].sort`

  * `[*].sort_options`

  * `[*]._editables`

  * `[*]._enabled_editors`

  * `[*]._inputs`

  * `[*]._select_data`

  * `[*]._structures`

  * `[*].add_options`

  * `[*].create`

  * `[*].disable_add`

  * `[*].disable_add_folder`

  * `[*].disable_file_actions`

  * `[*].new_preview_url`

  * `[*].schemas`

  * `[*].schema_key`

  * `[*].include_developer_files`
key_default: >-
  By default, CloudCannon uses your `source` key to make assumptions about your
  Collections.


  For more information, please read our documentation on
  [Collections](/documentation/articles/define-your-collections/).
documentation_link: /documentation/articles/define-your-collections/
parent_keys:
subkeys:
