_schema: default
glossary_term_name: Configuration cascade
term_description: >-
  A set of configuration sources with different scopes and priorities enabling
  global or collection-, schema-, file-, or input-specific configuration. 
documentation_link: /documentation/articles/using-the-configuration-cascade/
