_schema: default
glossary_term_name: Project
term_description: >-
  A collection of related sites and resources within CloudCannon that can be managed together. Projects help organize multiple websites that are part of the same initiative or belong to the same client.
documentation_link: /developer/articles/add-related-links-to-your-project/
