_schema: default
glossary_term_name: Project
term_description: >-
  A way to group multiple sites from the same Git Repository, allowing you to define a main branch, as well as branching and publishing rules.
documentation_link: /developer-articles/create-a-project/
