_schema: default
glossary_term_name: Routing
term_description: >-
  The process of determining how web requests are handled and which content is served based on the URL path. In CloudCannon, routing can include URL patterns, redirects, and geographic content delivery.
documentation_link: /developer/articles/configure-geolocation/
