_schema: default
glossary_term_name: Routing
term_description: >-
  The process of forwarding a visitor to a different webpage. By default, visitors see content for the file with a file name that matches the URL. However, routing is useful when you want to redirect old page URLs, configure extra headers, send visitors to a 404 page, remove URL extensions, or use geolocation.
documentation_link: /documentation/developer-articles/what-is-routing/
