_schema: default
glossary_term_name: App
term_description: >-
  The web-based CloudCannonapplication interface where users log in to manage their *Sites*, *Organizations*, and content. The CloudCannon App is available at https://app.cloudcannon.com.
documentation_link:

