name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check_links:
    name: Check Links
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno task build"

      - name: Run check
        run: "deno task check-links"
