name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .dvmrc
          cache: true

      - name: Run lint
        run: deno lint

      - name: Run TypeScript lint
        run: deno check --all

  check_links:
    name: Check Links and Images
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .dvmrc

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: _vendor
          key: deno-vendor-${{ runner.os }}-${{ hashFiles('deno.json', 'import_map.json', 'deno.lock', 'assets/js/site.js', '_includes/scripts/alpine.js') }}
          restore-keys: |
            deno-vendor-${{ runner.os }}-

      - name: Build step
        run: "deno task build"

      - name: Check links
        run: "deno task check-links"

      - name: Check images
        run: "deno task check-images"
